inherit_mode:
  merge:
    - Exclude
    - Include

Callbacksystems/ApplicationControllerMethodDefinition:
  Enabled: true
  Include:
    - "app/controllers/application_controller.rb"

Callbacksystems/BuilderMethodParentheses:
  Enabled: true
  Exclude:
    - "app/helpers/**/*"

Callbacksystems/CollapseMultilineExpression:
  Enabled: true
  MaxLineLength: 120

Callbacksystems/ComplexConditional:
  Enabled: true
  MaxOperators: 1

Callbacksystems/ControllerTestResponseAssertion:
  Enabled: true
  Include:
    - "test/controllers/**/*"

Callbacksystems/ControllerTestResponseFirstAssertion:
  Enabled: true
  Include:
    - "test/controllers/**/*"

Callbacksystems/DataClump:
  Enabled: true
  MinMethods: 3
  MinMethodsForSingleParam: 6

Callbacksystems/DeclarativeMethodNaming:
  Enabled: true

Callbacksystems/DelegateRequiresPrivateOption:
  Enabled: true

Callbacksystems/EagerLoadingScopeNaming:
  Enabled: true
  Include:
    - "app/models/**/*"

Callbacksystems/EarlyReturn:
  Enabled: true

Callbacksystems/EmptyLineBeforeMethod:
  Enabled: true
  DescribingMacros:
    - desc
    - long_desc
    - method_option
    - method_options
    - option

Callbacksystems/EmptyPrivateSection:
  Enabled: true

Callbacksystems/ExpandedEmptyClassOrModule:
  Enabled: true

Callbacksystems/InlineMemoizedComputation:
  Enabled: true

Callbacksystems/JobEnqueueMethods:
  Enabled: true
  Include:
    - "app/models/**/*"

Callbacksystems/MaxSafeNavigationDepth:
  Enabled: true
  MaxDepth: 3

Callbacksystems/MethodInvocationOrder:
  Enabled: true

Callbacksystems/MixinsFirst:
  Enabled: true

Callbacksystems/NestedClassesAtEndOfPrivateSection:
  Enabled: true

Callbacksystems/NoAbbreviations:
  Enabled: true

Callbacksystems/NoAnemicDelegation:
  Enabled: true

Callbacksystems/NoAssertSelect:
  Enabled: true
  Include:
    - "test/**/*"

Callbacksystems/NoBangMethodWithoutCounterpart:
  Enabled: true

Callbacksystems/NoCallMethod:
  Enabled: true

Callbacksystems/NoCommentsInTestClassBody:
  Enabled: true
  Include:
    - "test/**/*"

Callbacksystems/NoDirectEagerLoading:
  Enabled: true
  Include:
    - "app/controllers/**/*"

Callbacksystems/NoEachWithEarlyReturn:
  Enabled: true

Callbacksystems/NoExplicitPublicModifier:
  Enabled: true

Callbacksystems/NoHashWithDefaultBlock:
  Enabled: true

Callbacksystems/NoLocalVariableReturn:
  Enabled: true

Callbacksystems/NoManualAccumulation:
  Enabled: true

Callbacksystems/NoMixedMemoization:
  Enabled: true

Callbacksystems/NoNestedModulesInClasses:
  Enabled: true

Callbacksystems/NoNilAtEndOfMethod:
  Enabled: true

Callbacksystems/NoRedundantWrapperMethod:
  Enabled: true

Callbacksystems/NoSectionDividerComments:
  Enabled: true

Callbacksystems/NoSendInTests:
  Enabled: true
  Include:
    - "test/**/*"

Callbacksystems/NoServiceObjects:
  Enabled: true
  Include:
    - "app/**/*"

Callbacksystems/NoSingleLetterNames:
  Enabled: true

Callbacksystems/NoSingletonClassInModules:
  Enabled: true

Callbacksystems/NoTapCollectionBuilding:
  Enabled: true

Callbacksystems/NoTypographicClutter:
  Enabled: true

Callbacksystems/OrderedMixinArguments:
  Enabled: true

Callbacksystems/PluralControllerNames:
  Enabled: true
  IgnoredNames:
    - Application
    - Base
  Include:
    - "app/controllers/**/*"

Callbacksystems/PreferAttrReaderOverInstanceVariable:
  Enabled: true

Callbacksystems/PreferBackslashContinuation:
  Enabled: true

Callbacksystems/PreferClassForState:
  Enabled: true
  MinMethods: 4

Callbacksystems/PreferClassNewForEmptyNestedClass:
  Enabled: true

Callbacksystems/PreferClassOverBuilderBlock:
  Enabled: true

Callbacksystems/PreferDeclarativeCollections:
  Enabled: true

Callbacksystems/PreferDelegate:
  Enabled: true

Callbacksystems/PreferDelegateOverIvarAssignment:
  Enabled: true

Callbacksystems/PreferExcluding:
  Enabled: true

Callbacksystems/PreferItBlockParameter:
  Enabled: true

Callbacksystems/PreferMany:
  Enabled: true

Callbacksystems/PreferMethodOverVariable:
  Enabled: true
  Exclude:
    - "test/**/*"

Callbacksystems/PreferModuleForStaticClass:
  Enabled: true

Callbacksystems/PreferOrdinalArrayAccess:
  Enabled: true
  SafeAutoCorrect: false

Callbacksystems/PreferPositiveWrap:
  Enabled: true

Callbacksystems/PreferSquish:
  Enabled: true

Callbacksystems/PreferStringifyKeys:
  Enabled: true

Callbacksystems/PreferSymbolizeKeys:
  Enabled: true

Callbacksystems/PreferTurboPageRefreshBroadcasts:
  Enabled: true
  Include:
    - "app/**/*"

Callbacksystems/PrivateConstantsInPrivateSection:
  Enabled: true

Callbacksystems/PrivateDelegatePlacement:
  Enabled: true

Callbacksystems/PrivateMethodArgumentClump:
  Enabled: true
  MinParams: 2
  MinMethods: 2
  MinMethodsForSingleParam: 7
  Exclude:
    - "test/**/*"

Callbacksystems/PrivateMethodsInPrivateSection:
  Enabled: true

Callbacksystems/PrivateNestedClassMethodVisibility:
  Enabled: true

Callbacksystems/PrivateNestedClasses:
  Enabled: true

Callbacksystems/PublicMethodsMustHaveTests:
  Enabled: true
  Include:
    - "app/**/*"
    - "lib/**/*"
  Exclude:
    - "app/controllers/concerns/**/*"
    - "app/helpers/**/*"

Callbacksystems/RedundantConcernExtend:
  Enabled: true

Callbacksystems/RedundantConstantNamespace:
  Enabled: true

Callbacksystems/RepeatedFixtureInTests:
  Enabled: true
  Include:
    - "test/**/*"

Callbacksystems/RestrictedControllerActions:
  Enabled: true
  Include:
    - "app/controllers/**/*"

Callbacksystems/RoutesModuleScope:
  Enabled: true
  Include:
    - "config/routes.rb"
    - "config/routes/**/*"

Callbacksystems/SingleLineSetupBlock:
  Enabled: true
  Include:
    - "test/**/*"

Callbacksystems/SingleSingletonClass:
  Enabled: true

Callbacksystems/SingleTopLevelClassOrModule:
  Enabled: true

Callbacksystems/SingleUseFixtureVariable:
  Enabled: true
  Include:
    - "test/**/*"

Callbacksystems/SingleUseSetupVariable:
  Enabled: true
  Include:
    - "test/**/*"

Callbacksystems/SingularScopeNames:
  Enabled: true
  Include:
    - "app/models/**/*"

Callbacksystems/TestMethodDefinition:
  Enabled: true
  Include:
    - "test/**/*"

Callbacksystems/TestMethodOrder:
  Enabled: true
  Include:
    - "test/**/*"

Callbacksystems/TooManyInstanceVariables:
  Enabled: true
  MaxAssignments: 2

Callbacksystems/TooManyLocalVariables:
  Enabled: true
  MaxAssignments: 3

Callbacksystems/TooManyValidationGuards:
  Enabled: true
  MaxGuards: 2

Callbacksystems/UnnecessaryLocalVariable:
  Enabled: true
  Exclude:
    - "app/controllers/**/*"
    - "test/**/*"

Callbacksystems/UnusedPrivateMethodInNestedClass:
  Enabled: true
