# Built from the cops themselves. The sentence opening each cop's file is its
# description here and in `config/default.yml`, so neither is written twice.
class CopReference
  ROOT = File.expand_path("../..", __dir__)
  COP_DIR = "lib/rubocop/cop/callbacksystems"
  CONFIG_PATH = "config/default.yml"
  DOCUMENT_PATH = "docs/README.md"

  PREAMBLE = <<~MARKDOWN
    # Cops

    <!-- Generated by `UPDATE_DOCS=1 bin/test`. Do not edit by hand. -->

    Every cop lives under the `Callbacksystems/` namespace and is on by default.
    Each one links to its source, where the header comment explains what it is for
    and why, and an `@example` block contrasts bad and good code.

    Options and the paths a cop applies to are in
    [`config/default.yml`](../config/default.yml).

    | Cop | Fix | Description |
    |---|---|---|
  MARKDOWN

  def document
    "#{PREAMBLE}#{cops.map { row_for(it) }.join}"
  end

  def cops
    @cops ||= RuboCop::Cop::Registry.global.cops.select { own?(it) }.sort_by(&:cop_name).map { Cop.new(it) }
  end

  # Edited line by line rather than round-tripped through YAML, which would
  # drop the comments and the order the file is kept in.
  def configured
    described_lines.join("\n")
  end

  private
    def own?(cop_class)
      cop_class.badge.department == :Callbacksystems
    end

    def row_for(cop)
      "| [`#{cop.name}`](../#{cop.path}) | #{cop.fix} | #{cop.description} |\n"
    end

    def described_lines
      config_lines.flat_map { description_for(it) || it }
    end

    def config_lines
      File.read(File.join(ROOT, CONFIG_PATH)).split("\n").reject { it.start_with?("  Description:") }
    end

    # Quoted by YAML itself: prose holding a colon, a backslash or a leading
    # backtick each needs different quoting.
    def description_for(line)
      cop = cops.find { line == "#{it.badge}:" }
      [ line, "  Description: #{YAML.dump(cop.description, line_width: -1).delete_prefix("---").strip}" ] if cop
    end

    class Cop
      def initialize(cop_class)
        @cop_class = cop_class
      end

      def badge
        cop_class.badge.to_s
      end

      def fix
        cop_class.support_autocorrect? ? "yes" : ""
      end

      # A pipe would end the table cell it sits in.
      def description
        header.gsub("|", "\\|")
      end

      def path
        "#{COP_DIR}/#{name.underscore}.rb"
      end

      def name
        cop_class.badge.cop_name
      end

      private
        attr_reader :cop_class

        def header
          summary[/\A.*?\.(?=\s|\z)/] || summary
        end

        def summary
          opening_comment.map { it.delete_prefix("#").strip }.join(" ")
        end

        def opening_comment
          File.readlines(File.join(ROOT, path), chomp: true)
            .take_while { it.start_with?("#") }
            .take_while { it != "#" }
        end
    end
end
