require "yaml"

class RuboCop::Callbacksystems::CopsDocument
  DEFAULT_PATH = File.expand_path("../../../docs/cops.md", __dir__)
  HEADING = <<~MARKDOWN
    # Cops

    <!-- Generated by `bin/docs`. Do not edit by hand. -->

    Every cop lives under the `Callbacksystems/` namespace and ships enabled. Each one links to its source, where an `@example` block contrasts the code it rejects with the code it asks for, and `config/default.yml` holds its options and default scope.
  MARKDOWN
  TABLE_HEADER = [ "| Cop | Autocorrect | Description |", "|---|---|---|" ]

  def initialize(path = DEFAULT_PATH)
    @path = path
  end

  def save
    File.write path, text
  end

  def text
    [ HEADING, *TABLE_HEADER, *rows, "" ].join("\n")
  end

  def committed
    File.read(path)
  end

  def undescribed
    rows.select { it.description.blank? }.map(&:name)
  end

  private
    SOURCE_DIRECTORY = "../lib/rubocop/cop/callbacksystems"

    attr_reader :path

    def rows
      @rows ||= cops.map { Row.new(it, descriptions[it.cop_name]) }
    end

    def cops
      RuboCop::Cop::Registry.global.cops.select { it.department == :Callbacksystems }.sort_by(&:cop_name)
    end

    def descriptions
      YAML.load_file(RuboCop::Callbacksystems::Plugin::CONFIGURATION_PATH).transform_values { it["Description"] }
    end

    class Row
      attr_reader :description

      def initialize(cop, description)
        @cop = cop
        @description = description
      end

      def to_s
        "| [`#{name}`](#{source_path}) | #{autocorrection} | #{description} |"
      end

      def name
        cop.cop_name
      end

      private
        attr_reader :cop

        def source_path
          "#{SOURCE_DIRECTORY}/#{cop.badge.cop_name.underscore}.rb"
        end

        def autocorrection
          "yes" if cop.support_autocorrect?
        end
    end
end
